//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignStudent.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForeignStudent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ItemList&gt;
        ///&lt;Item Code=&quot;0&quot; CH=&quot;中華民國&quot; EN=&quot;R.O.C&quot; /&gt;
        ///&lt;Item Code=&quot;1&quot; CH=&quot;阿富汗&quot; EN=&quot;AFGHANISTAN&quot; /&gt;
        ///&lt;Item Code=&quot;2&quot; CH=&quot;巴林&quot; EN=&quot;BAHRAIN&quot; /&gt;
        ///&lt;Item Code=&quot;3&quot; CH=&quot;孟加拉&quot; EN=&quot;BANGLADESH&quot; /&gt;
        ///&lt;Item Code=&quot;4&quot; CH=&quot;不丹&quot; EN=&quot;BHUTAN&quot; /&gt;
        ///&lt;Item Code=&quot;5&quot; CH=&quot;緬甸&quot; EN=&quot;BURMA&quot; /&gt;
        ///&lt;Item Code=&quot;6&quot; CH=&quot;柬埔寨&quot; EN=&quot;CAMBODIA&quot; /&gt;
        ///&lt;Item Code=&quot;7&quot; CH=&quot;賽浦勒斯&quot; EN=&quot;CYPRUS&quot; /&gt;
        ///&lt;Item Code=&quot;8&quot; CH=&quot;印度&quot; EN=&quot;INDIA&quot; /&gt;
        ///&lt;Item Code=&quot;9&quot; CH=&quot;印尼&quot; EN=&quot;INDONESIA&quot; /&gt;
        ///&lt;Item Code=&quot;10&quot; CH=&quot;伊朗&quot; EN=&quot;IRAN&quot; /&gt;
        ///&lt;Item Code=&quot;11&quot; CH=&quot;伊拉克&quot; EN=&quot;IRAQ&quot; /&gt;
        ///&lt;Item Code=&quot;12&quot; CH=&quot;以色列&quot; EN [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] Template {
            get {
                object obj = ResourceManager.GetObject("Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
